---
title: "stat297hw2"
author: "Ryan Voyack, Andrea Wan, Marshall Malino"
date: "October 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Fizz Buzz
```{r something} 
for (i in 1:1000){
  
  if (i %%3 ==0){
    cat('fizz')
  }
  if (i %% 5 ==0){
    cat('buzz')
  }
  if ((i %%3 != 0) && (i%%5!=0)){
    cat(i)
  } 
  cat(' ')
}
```

### Map 
```{r givenchunk1, cache=TRUE}
library(maps)
library(ggmap)
library(rvest)

# Define webpage
big10 = read_html("http://www.bigten.org/library/stats/fb-confsked.html#standings")

# Get uni names
big10 %>% 
    html_nodes(".b1gfbstats:nth-child(9) td:nth-child(1) , .b1gfbstats:nth-child(6) td:nth-child(1)") %>% 
    html_text() -> uni_name
uni_name = paste(uni_name,"University")

# Find uni locations
uni_coord = data.frame(geocode(uni_name))

# Get win rate
big10 %>% 
    html_nodes("td:nth-child(7)") %>%
    html_text() -> uni_wp
uni_coord$wp = 100*as.numeric(uni_wp[1:length(uni_name)])

# Get division
uni_coord$conf = rep(c("East Division","West Division"), each = length(uni_name)/2)
```

```{r mapsetup, cache=TRUE}
library(mapproj)
map <- get_map(location = ("Indiana"), color="bw", zoom = 4, maptype = "toner-background")
```

```{r map}
names(uni_coord)[names(uni_coord)=="conf"]<-"division"

MAP <- ggmap(map) + xlim(from=-105, to=-72) + ylim(from=35, to=50) + xlab("Longitude") + ylab("Latitude")

MAP <- MAP + geom_point(data=uni_coord, aes(lon, lat, col = division, size = wp)) + ggtitle("Big 10 Conference - as of 2017-10-07")

MAP + scale_size(name= 'Win Rate [%]')
```

### 3d Random Walks

* **(a)** Show that Xb = <26, -44, 26> 

* **(a)** Show that Xb = <26, -44, 26> 

```{r createfunction}
f <- function(i, X){
  i=i-1
  U <- Ut[i]  

  if(U<=(1/6)){
    U <- c(1,0,0)
    return(X + U)
  }else if(U<=(2/6)){
    U <- c(-1,0,0)
    return(X + U)
  }else if(U<=(3/6)){
    U <- c(0,1,0)
    return(X + U)
  }else if(U<=(4/6)){
  U <- c(0,-1,0)
    return(X + U)
  }else if(U<=(5/6)){
    U <- c(0,0,1)
    return(X + U)
  }else if(U<=1){
    U <- c(0,0,-1)
    return(X + U)
  }else{
    return(X)
  }
}
```


```{r partA, echo=FALSE}
B <- 10^4
set.seed(1982)
Ut <- runif(B)
head(Ut)

B=B+1 #so we could make the first column (coordinate set) of our matrix the original position
positions <- matrix(NA, 3, B)
X = c(0,0,0) #our Xo, our starting position


for(i in (1:(B))){
  if(i!=1){
    X <- f(i,X)
  }
  positions[,i] <- X
}

X #this is our Xb
```


```{r createPlot}
xyz0positions <- positions[,1:10000]
x0<-xyz0positions[1,] 
y0<-xyz0positions[2,] 
z0<-xyz0positions[3,] 

x1<-positions[1,-1] 
y1<-positions[2,-1] 
z1<-positions[3,-1] 


library(plot3D)

(segments3D(x0,y0,z0,x1,y1,z1,xlab='',ylab='',zlab='', bty = 'g',ticktype = 'detailed',phi=0))
scatter3D(0,0,0,pch=20, cex=2, add=TRUE, col='red')
scatter3D(x0[10000],y0[10000],z0[10000],pch=20, cex=2, add=TRUE, col='blue')
```

### Portfolio
```library(quantmod)
library(rvest)
sp500 <- read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")

sp500 %>% 
  html_nodes(".text") %>% 
  html_text() -> ticker_sp500

SP500_symbol <- ticker_sp500[(1:499)*2+1]
SP500_symbol[SP500_symbol == "BRK.B"] <- "BRK-B"
SP500_symbol[SP500_symbol == "BF.B"] <- "BF-B"


today <- Sys.Date()
three_year_ago <- seq(today, length = 2, by = "-3 year")[2]
getSymbols(SP500_symbol, from = three_year_ago, to = today)

N = length(tick)
OM_MAT = matrix(NA,N,N)

for(j in 1:(N-1)){
  for(i in (j+1):N){
    S1= get(tick[i])
    S2 = get(tick[j])
    cost = max(40, 0.0001*10^6*S1)+max(40, 0.0001*10^6 *S2)
  }
}
```
